### ISSUE TITLE
Unexpected Error Occurred

### ISSUE THREAD

**Issue by hypnos83829** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#170]
---------------------------
Unexpected Error Occurred: Dispatcher.UnhandledException
---------------------------
The following exception occurred:

System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'EnhancePoE.MainWindow' that matches the specified binding constraints threw an exception. ---> System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: '.', hexadecimal value 0x00, is an invalid character. Line 16, position 1. (C:\Users\14403\AppData\Local\EnhancePoE\EnhancePoE.exe_Url_tiwzio3q2nsjjtntfmfqa1vzrotkyiak\1.0.0.0\user.config line 16) ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 16, position 1.

   at System.Xml.XmlTextReaderImpl.Throw(Exception e)

   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)

   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)

   at System.Xml.XmlTextReaderImpl.ParseText()

   at System.Xml.XmlTextReaderImpl.ParseElementContent()

   at System.Xml.XmlTextReaderImpl.Read()

   at System.Xml.XmlTextReader.Read()

   at System.Xml.XmlTextReaderImpl.Skip()

   at System.Xml.XmlTextReader.Skip()

   at System.Configuration.XmlUtil.StrictSkipToNextElement(ExceptionAction action)

   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)

   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)

   at System.Configuration.BaseConfigurationRecord.ScanSections(XmlUtil xmlUtil)

   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

   --- End of inner exception stack trace ---

   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)

   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)

   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()

   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)

   --- End of inner exception stack trace ---

   at System.Configuration.ConfigurationManager.PrepareConfigSystem()

   at System.Configuration.ConfigurationManager.RefreshSection(String sectionName)

   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)

   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)

   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)

   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)

   at System.Configuration.SettingsBase.get_Item(String propertyName)

   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)

   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)

   at EnhancePoE.Properties.Settings.get_ColorBoots()

   at EnhancePoE.MainWindow.InitializeColors()

   at EnhancePoE.MainWindow..ctor()

   --- End of inner exception stack trace ---

   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)

   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)

   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)

   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)

   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)

   at System.Windows.Application.DoStartup()

   at System.Windows.Application.<.ctor>b__1_0(Object unused)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Please report this issue on github or discord :)
---------------------------
OK   
---------------------------

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Also gonna close this one due to age.

Please re-open a new issue if you need anything else! Thanks for your report.
