### ISSUE TITLE
Unexpected error occurred: AppDomain.CurrentDomain.UnhandledExpectation

### ISSUE THREAD

**Issue by lMercilessl** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#173]
---------------------------
Unexpected Error Occurred: AppDomain.CurrentDomain.UnhandledException
---------------------------
The following exception occurred:

System.Threading.Tasks.TaskCanceledException: A task was canceled.

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at EnhancePoE.ApiAdapter.<GetItems>d__21.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at EnhancePoE.ChaosRecipeEnhancer.<<FetchData>b__129_1>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at EnhancePoE.ChaosRecipeEnhancer.<FetchData>d__129.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)

   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
---------------------------
OK   
---------------------------

Got this error while fetching.

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Also gonna close this one due to age.

Please re-open a new issue if you need anything else! Thanks for your report.
