### ISSUE TITLE
Exception when using online loot filter

### ISSUE THREAD

**Issue by scainburger** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#188]
I get the following error when trying to use an online filter. I'm confident the name is set correctly as I have copy pasted it directly from item filters on my profile. See below.

```
---------------------------
Unexpected Error Occurred: Dispatcher.UnhandledException
---------------------------
The following exception occurred:

System.NullReferenceException: Object reference not set to an instance of an object.

   at EnhancePoE.Model.FilterGeneration.GenerateLootFilter(String oldFilter, HashSet`1 sections)

   at EnhancePoE.Data.<CheckActives>d__71.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at EnhancePoE.ChaosRecipeEnhancer.<<FetchData>b__129_3>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at EnhancePoE.ChaosRecipeEnhancer.<<FetchData>b__129_1>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at EnhancePoE.ChaosRecipeEnhancer.<FetchData>d__129.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by etaus** [comment]
I have the same error. Except I don't use online filter. .NET Framework is up to date (version 4.7.2).

**Comment by scainburger** [comment]
Weird. I don't get the error when using a local filter.

**Comment by etaus** [comment]
I tried with online filter and in both cases after I click to fetch items I get this error.

**Comment by flbraun** [comment]
Exact same error for me, pops up after fetching :/

**Comment by kosace** [comment]
I have added error messages for that case in the newest version. The online filter does not work with followed filters or if the filtername is incorrect. Reopen if issue persists in 1.2.4

**Comment by scainburger** [comment]
> The online filter does not work with followed filters

Sorry, maybe I misunderstand the purpose of this feature. What is it supposed to work with if not followed filters?

**Comment by kosace** [comment]
For example on filterblade you can save your lootfilter to your account. That way the filter belongs to you and you can do whatever you want to them.
But if you follow a filter from a friend or something the filter belongs to them and you cannot change it. Only they can change it.

See the screenshot for reference.
![Screenshot 2021-07-28 141519](https://user-images.githubusercontent.com/38064380/127320620-a07db69b-b619-45a7-b797-c3c5df5bad08.jpg)
