### ISSUE TITLE
[Bug] [Unsorted] crash on fetch

### ISSUE THREAD

**Issue by ChaosDMG** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#565]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest release (not a beta / pre-release)
- [ ] I checked the FAQ and found no common resolution for my issue
- [ ] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version:
* Operating System:
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by ChaosDMG** [comment]
Reporting an exception I received while using Chaos Recipe Enhancer v3.23.1005:
```
The following exception occurred: Dispatcher.UnhandledExceptionSystem.InvalidOperationException: The given header was not found.
   at System.Net.Http.Headers.HttpHeaders.GetValues(HeaderDescriptor descriptor)
   at ChaosRecipeEnhancer.UI.Services.ApiService.GetAuthenticatedAsync(Uri requestUri) in D:\PoE Tools\ChaosRecipeEnhancer\EnhancePoEApp\src\App\ChaosRecipeEnhancer.UI\Services\ApiService.cs:line 132
   at ChaosRecipeEnhancer.UI.Services.ApiService.GetPersonalStashTabContentsByStashIdAsync(String stashId) in D:\PoE Tools\ChaosRecipeEnhancer\EnhancePoEApp\src\App\ChaosRecipeEnhancer.UI\Services\ApiService.cs:line 52
   at ChaosRecipeEnhancer.UI.Windows.SetTrackerOverlayViewModel.FetchStashDataAsync() in D:\PoE Tools\ChaosRecipeEnhancer\EnhancePoEApp\src\App\ChaosRecipeEnhancer.UI\Windows\SetTrackerOverlayViewModel.cs:line 155
```

**Comment by SkiaAoP** [comment]
I am also crashing every 1-2 maps. Overlay will disappear and CRE settings window will CTD.

**Comment by HiMarioLopez** [comment]
Closing as duplicate: https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/issues/575

Will review the errors emitted by GGG's services and more gracefully handle the errors for the next release. Thanks!
