### ISSUE TITLE
[Bug] [Unsorted] got an error that just told me to copy and paste here

### ISSUE THREAD

**Issue by chengsta** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#572]
When clicking the stash button ui, the error below popped up.  Mind you, I have an annoying issue with my mouse doubleclicking whatever i click once.  It happens 50% of the time no matter what mouse I use.  And the mouse is fine in other computers.  It's got either something to do with my computer hardware, or the OS itself.  lots of other people have same issue, so it's probably a windows thing.

Reporting an exception I received while using Chaos Recipe Enhancer v3.23.1005:
```
The following exception occurred: AppDomain.CurrentDomain.UnhandledExceptionSystem.InvalidOperationException: This Visual is not connected to a PresentationSource.
   at System.Windows.Media.Visual.PointToScreen(Point point)
   at ChaosRecipeEnhancer.UI.UserControls.StashTab.Coordinates.GetTabNameContainerCoordinates(Visual tabNameContainer) in D:\PoE Tools\ChaosRecipeEnhancer\EnhancePoEApp\src\App\ChaosRecipeEnhancer.UI\UserControls\StashTab\Coordinates.cs:line 53
   at ChaosRecipeEnhancer.UI.UserControls.StashTab.Coordinates.CheckIfTabNameContainerClicked(StashTabControl stashTabControl) in D:\PoE Tools\ChaosRecipeEnhancer\EnhancePoEApp\src\App\ChaosRecipeEnhancer.UI\UserControls\StashTab\Coordinates.cs:line 73
   at ChaosRecipeEnhancer.UI.UserControls.StashTab.Coordinates.OverlayClickEvent(StashTabOverlayWindow stashTabOverlayWindow) in D:\PoE Tools\ChaosRecipeEnhancer\EnhancePoEApp\src\App\ChaosRecipeEnhancer.UI\UserControls\StashTab\Coordinates.cs:line 123
```

**Comment by HiMarioLopez** [comment]
should be solved in #585
