### ISSUE TITLE
Unhandled Exception - Dispatcher.UnhandledException

### ISSUE THREAD

**Issue by Amiral1212** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#573]
Reporting an exception I received while using Chaos Recipe Enhancer v3.23.1005:
```
The following exception occurred: Dispatcher.UnhandledExceptionSystem.InvalidOperationException: The given header was not found.
   at System.Net.Http.Headers.HttpHeaders.GetValues(HeaderDescriptor descriptor)
   at ChaosRecipeEnhancer.UI.Services.ApiService.GetAuthenticatedAsync(Uri requestUri) in D:\PoE Tools\ChaosRecipeEnhancer\EnhancePoEApp\src\App\ChaosRecipeEnhancer.UI\Services\ApiService.cs:line 132
   at ChaosRecipeEnhancer.UI.Services.ApiService.GetPersonalStashTabContentsByStashIdAsync(String stashId) in D:\PoE Tools\ChaosRecipeEnhancer\EnhancePoEApp\src\App\ChaosRecipeEnhancer.UI\Services\ApiService.cs:line 52
   at ChaosRecipeEnhancer.UI.Windows.SetTrackerOverlayViewModel.FetchStashDataAsync() in D:\PoE Tools\ChaosRecipeEnhancer\EnhancePoEApp\src\App\ChaosRecipeEnhancer.UI\Windows\SetTrackerOverlayViewModel.cs:line 155
```

**Comment by JWWolstenholme** [comment]
I also get the exact same error. This only occurs on some fetches. Sometimes it crashes without showing the crash handler.

Reporting an exception I received while using Chaos Recipe Enhancer v3.23.1005:
```
The following exception occurred: Dispatcher.UnhandledExceptionSystem.InvalidOperationException: The given header was not found.
   at System.Net.Http.Headers.HttpHeaders.GetValues(HeaderDescriptor descriptor)
   at ChaosRecipeEnhancer.UI.Services.ApiService.GetAuthenticatedAsync(Uri requestUri) in D:\PoE Tools\ChaosRecipeEnhancer\EnhancePoEApp\src\App\ChaosRecipeEnhancer.UI\Services\ApiService.cs:line 132
   at ChaosRecipeEnhancer.UI.Services.ApiService.GetPersonalStashTabContentsByStashIdAsync(String stashId) in D:\PoE Tools\ChaosRecipeEnhancer\EnhancePoEApp\src\App\ChaosRecipeEnhancer.UI\Services\ApiService.cs:line 52
   at ChaosRecipeEnhancer.UI.Windows.SetTrackerOverlayViewModel.FetchStashDataAsync() in D:\PoE Tools\ChaosRecipeEnhancer\EnhancePoEApp\src\App\ChaosRecipeEnhancer.UI\Windows\SetTrackerOverlayViewModel.cs:line 155
```

**Comment by acpirience** [comment]
Same here, happens at minimum every 5-10 minutes.


Reporting an exception I received while using Chaos Recipe Enhancer v3.23.1005:
```
The following exception occurred: Dispatcher.UnhandledExceptionSystem.InvalidOperationException: The given header was not found.
   at System.Net.Http.Headers.HttpHeaders.GetValues(HeaderDescriptor descriptor)
   at ChaosRecipeEnhancer.UI.Services.ApiService.GetAuthenticatedAsync(Uri requestUri) in D:\PoE Tools\ChaosRecipeEnhancer\EnhancePoEApp\src\App\ChaosRecipeEnhancer.UI\Services\ApiService.cs:line 132
   at ChaosRecipeEnhancer.UI.Services.ApiService.GetAllPersonalStashTabMetadataAsync() in D:\PoE Tools\ChaosRecipeEnhancer\EnhancePoEApp\src\App\ChaosRecipeEnhancer.UI\Services\ApiService.cs:line 41
   at ChaosRecipeEnhancer.UI.UserControls.SettingsForms.GeneralForms.GeneralFormViewModel.LoadStashTabNamesIndicesAsync() in D:\PoE Tools\ChaosRecipeEnhancer\EnhancePoEApp\src\App\ChaosRecipeEnhancer.UI\UserControls\SettingsForms\GeneralForms\GeneralFormViewModel.cs:line 115
```

**Comment by HiMarioLopez** [comment]
Closing as duplicate: https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/issues/575

Will review the errors emitted by GGG's services and more gracefully handle the errors for the next release. Thanks!
