### ISSUE TITLE
[Bug] [Unsorted] *cashing*

### ISSUE THREAD

**Issue by robyrollover** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#574]
Reporting an exception I received while using Chaos Recipe Enhancer v3.23.1005:
```
The following exception occurred: Dispatcher.UnhandledExceptionSystem.Net.Http.HttpRequestException: No such host is known. (api.pathofexile.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
```

happens when i fetch

**Comment by HiMarioLopez** [comment]
Closing as duplicate: https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/issues/575

Will review the errors emitted by GGG's services and more gracefully handle the errors for the next release. Thanks!
