### ISSUE TITLE
Notice: CRE will be unusable while PoE services are getting DDoS'd.

### ISSUE THREAD

**Issue by elvese** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#576]
Reporting an exception I received while using Chaos Recipe Enhancer v3.23.1005:
```
The following exception occurred: Dispatcher.UnhandledExceptionSystem.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
```

**Comment by voidisme** [comment]
Same issue here. I get also after reinstalling.

Reporting an exception I received while using Chaos Recipe Enhancer v3.23.1005:
```
The following exception occurred: Dispatcher.UnhandledExceptionSystem.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
```

edit: I uninstalled chaos enhancer, restarted computer and updated to latest .net, seems to be fine now

**Comment by HiMarioLopez** [comment]
No need to reinstall. The PoE services are getting DDoS'd today. The app (as well as other 3rd party apps, like the Trade Macro) will not work until these issues are resolved. There's nothing I can do about it at the moment, unfortunately.
