### ISSUE TITLE
[Bug] [General] UnhandledExceptionNAudio.MmException: BadDeviceId calling waveOutOpen

### ISSUE THREAD

**Issue by ezbooz** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#596]
Reporting an exception I received while using Chaos Recipe Enhancer v3.24.2000:

Error Details:
```
The following exception occurred: Dispatcher.UnhandledExceptionNAudio.MmException: BadDeviceId calling waveOutOpen
   at NAudio.MmException.Try(MmResult result, String function)
   at NAudio.Wave.WaveOutEvent.Init(IWaveProvider waveProvider)
   at ChaosRecipeEnhancer.UI.Services.AudioResource..ctor(String filePath) in D:\PoE Tools\ChaosRecipeEnhancer\ChaosRecipeEnhancer\src\App\ChaosRecipeEnhancer.UI\Services\NotificationSoundService.cs:line 90
   at ChaosRecipeEnhancer.UI.Services.NotificationSoundService..ctor(IUserSettings userSettings) in D:\PoE Tools\ChaosRecipeEnhancer\ChaosRecipeEnhancer\src\App\ChaosRecipeEnhancer.UI\Services\NotificationSoundService.cs:line 24
```

![image](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/assets/55065112/8e998342-ede7-4469-ac54-b6696d4111d7)

**Comment by HiMarioLopez** [comment]
While I did roll back the 3.24 releases, this is a bug I will keep open. I want to re-release the changes introduced in 3.24, including sounds.

I’ll dig into this and see what went wrong, thanks!

**Comment by HiMarioLopez** [comment]
Go ahead and completely unisntall any old versions of the app, and reinstall our latest (re)release here: https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/releases/tag/3.24.3000

let me know if you run into any issues. thanks
