### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by DezZzO** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#597]
Reporting an exception I received while using Chaos Recipe Enhancer v3.24.2000:

Error Context:
```
It looks like your credentials have expired. Please log back in to continue.
```
Error Details:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ChaosRecipeEnhancer.UI.Services.GlobalItemSetManagerState.FlattenStashTabs(ListStashesResponse response) in D:\PoE Tools\ChaosRecipeEnhancer\ChaosRecipeEnhancer\src\App\ChaosRecipeEnhancer.UI\Services\GlobalItemSetManagerState.cs:line 483
   at ChaosRecipeEnhancer.UI.Windows.SetTrackerOverlayViewModel.FetchStashDataAsync() in D:\PoE Tools\ChaosRecipeEnhancer\ChaosRecipeEnhancer\src\App\ChaosRecipeEnhancer.UI\Windows\SetTrackerOverlayViewModel.cs:line 179
```

**Comment by HiMarioLopez** [comment]
3.24 launch did not go as intended. I’ve since removed those releases and their associated installers, and rolled back all associated backend components.

I will be review what went wrong - for the meanwhile 3.23.1005 is the latest stable release.

You can find the latest installers here: https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/releases
