### ISSUE TITLE
[Bug] [Unsorted] *Brief synopsis of your issue*

### ISSUE THREAD

**Issue by i3rinkmann** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#614]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest release (not a beta / pre-release)
- [x] I checked the FAQ and found no common resolution for my issue
- [x] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

When i fetch (manually or zone switching) the overlay updates.

# Current Behavior

It hard crasches

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. fetch
2. crash

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version:  3.24.3001
* Operating System: Windows 10
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <userSettings>
        <ChaosRecipeEnhancer.UI.Properties.Settings>
            <setting name="PathOfExileAccountName" serializeAs="String">
                <value>i3*</value>
            </setting>
            <setting name="PoEAccountConnectionStatus" serializeAs="String">
                <value>1</value>
            </setting>
            <setting name="ChaosRecipeTrackingEnabled" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="FullSetThreshold" serializeAs="String">
                <value>1</value>
            </setting>
            <setting name="LeagueName" serializeAs="String">
                <value>SSF Necropolis</value>
            </setting>
            <setting name="StashTabIndices" serializeAs="String">
                <value>3</value>
            </setting>
            <setting name="AutoFetchOnRezoneEnabled" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="PathOfExileClientLogLocation" serializeAs="String">
                <value>C:\Program Files (x86)\Steam\SteamApps\common\Path of Exile\logs\Client.txt</value>
            </setting>
            <setting name="SetTrackerOverlayItemCounterDisplayMode" serializeAs="String">
                <value>2</value>
            </setting>
            <setting name="SetTrackerOverlayDisplayMode" serializeAs="String">
                <value>2</value>
            </setting>
            <setting name="SetTrackerOverlayTopPosition" serializeAs="String">
                <value>1337</value>
            </setting>
            <setting name="SetTrackerOverlayLeftPosition" serializeAs="String">
                <value>739</value>
            </setting>
            <setting name="StashTabOverlayTopPosition" serializeAs="String">
                <value>94</value>
            </setting>
            <setting name="StashTabOverlayLeftPosition" serializeAs="String">
                <value>14</value>
            </setting>
            <setting name="StashTabOverlayHeight" serializeAs="String">
                <value>922</value>
            </setting>
            <setting name="StashTabOverlayWidth" serializeAs="String">
                <value>856</value>
            </setting>
            <setting name="DebugMode" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="UpgradeSettingsAfterUpdate" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="PathOfExileApiAuthTokenExpiration" serializeAs="String">
                <value>05/06/2024 16:52:35</value>
            </setting>
            <setting name="PathOfExileApiAuthToken" serializeAs="String">
                <value>5d*******</value>
            </setting>
            <setting name="VendorSetsEarly" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="FetchStashHotkey" serializeAs="String">
                <value>Ctrl + D7</value>
            </setting>
            <setting name="ToggleSetTrackerOverlayHotkey" serializeAs="String">
                <value>D8</value>
            </setting>
            <setting name="ToggleStashTabOverlayHotkey" serializeAs="String">
                <value>D9</value>
            </setting>
            <setting name="SettingsWindowNavIndex" serializeAs="String">
                <value>1</value>
            </setting>
        </ChaosRecipeEnhancer.UI.Properties.Settings>
    </userSettings>
</configuration>
```

## Failure Logs
Reporting an exception I received while using Chaos Recipe Enhancer 3.24.3001:

Error Details:
```
The following exception occurred: Dispatcher.UnhandledExceptionSystem.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at ChaosRecipeEnhancer.UI.Services.GlobalItemSetManagerState.GenerateItemSets_Greedy(List`1 eligibleRecipeItems, Int32 trueSetThreshold, Boolean regalRecipe) in D:\PoE Tools\ChaosRecipeEnhancer\ChaosRecipeEnhancer\src\App\ChaosRecipeEnhancer.UI\Services\GlobalItemSetManagerState.cs:line 372
   at ChaosRecipeEnhancer.UI.Services.GlobalItemSetManagerState.GenerateItemSets(Boolean regalRecipe) in D:\PoE Tools\ChaosRecipeEnhancer\ChaosRecipeEnhancer\src\App\ChaosRecipeEnhancer.UI\Services\GlobalItemSetManagerState.cs:line 198
   at ChaosRecipeEnhancer.UI.Windows.SetTrackerOverlayViewModel.FetchStashDataAsync() in D:\PoE Tools\ChaosRecipeEnhancer\ChaosRecipeEnhancer\src\App\ChaosRecipeEnhancer.UI\Windows\SetTrackerOverlayViewModel.cs:line 286
   at ChaosRecipeEnhancer.UI.Windows.SetTrackerOverlayWindow.RunFetchingAsync() in D:\PoE Tools\ChaosRecipeEnhancer\ChaosRecipeEnhancer\src\App\ChaosRecipeEnhancer.UI\Windows\SetTrackerOverlayWindow.xaml.cs:line 132
```

**Comment by infinityover** [comment]
I have same issue, tried to uninstall and install again, clear localdata files, nothing solves this problem for me

**Comment by HiMarioLopez** [comment]
Issue should be fixed with the latest release. Apologies for that.
https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/releases
