### ISSUE TITLE
[Bug] [Unsorted] *Brief synopsis of your issue*

### ISSUE THREAD

**Issue by UKWoody** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#639]
Reporting an exception I received while using Chaos Recipe Enhancer 3.25.1001:

Error Details:
```
The following exception occurred: Dispatcher.UnhandledExceptionSystem.Windows.Markup.XamlParseException: The invocation of the constructor on type 'ChaosRecipeEnhancer.UI.UserControls.SettingsForms.LootFilterForms.LootFilterManipulationForm' that matches the specified binding constraints threw an exception.
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Windows\system32\Assets\Sounds\ItemSetStateChanged.wav'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
```

**Comment by ANNOYEDCHERRY** [comment]
I got a similar exception when I loaded up Chaos Recipe 3.25.1001

Reporting an exception I received while using Chaos Recipe Enhancer v3.23.1005:
```
The following exception occurred: Dispatcher.UnhandledExceptionSystem.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
```

**Comment by HiMarioLopez** [comment]
You will need to upgrade to the latest version to resolve this issue

thanks 

https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/releases
