### ISSUE TITLE
[Bug] [Unsorted] STA Error

### ISSUE THREAD

**Issue by ImVexed** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#641]
Reporting an exception I received while using Chaos Recipe Enhancer 3.25.1001:

Error Details:
```
The following exception occurred: AppDomain.CurrentDomain.UnhandledExceptionSystem.InvalidOperationException: The calling thread must be STA, because many UI components require this.
   at System.Windows.Input.InputManager..ctor()
   at System.Windows.Input.InputManager.GetCurrentInputManagerImpl()
   at System.Windows.Input.KeyboardNavigation..ctor()
   at System.Windows.FrameworkElement.FrameworkServices..ctor()
```

**Comment by Sing0424** [comment]
Same issue here

**Comment by Diabolos** [comment]
Also me:

Reporting an exception I received while using Chaos Recipe Enhancer 3.25.1001:

Error Details:
```
The following exception occurred: AppDomain.CurrentDomain.UnhandledExceptionSystem.InvalidOperationException: The calling thread must be STA, because many UI components require this.
   at System.Windows.Input.InputManager..ctor()
   at System.Windows.Input.InputManager.GetCurrentInputManagerImpl()
   at System.Windows.Input.KeyboardNavigation..ctor()
   at System.Windows.FrameworkElement.FrameworkServices..ctor()
```

**Comment by dwiggins5091** [comment]
Same

The following exception occurred: AppDomain.CurrentDomain.UnhandledExceptionSystem.InvalidOperationException: The calling thread must be STA, because many UI components require this.
   at System.Windows.Input.InputManager..ctor()
   at System.Windows.Input.InputManager.GetCurrentInputManagerImpl()
   at System.Windows.Input.KeyboardNavigation..ctor()
   at System.Windows.FrameworkElement.FrameworkServices..ctor()

**Comment by dwiggins5091** [comment]
https://chatgpt.com/share/6753bbd1-0dd0-8012-b06c-ede25b68bf6a <- Resolution for the source code update

**Comment by HiMarioLopez** [comment]
fixed: https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/pull/663
